import SheetEditor from "../SheetEditor";

// Available icons from lucide-react
const availableIcons = [
  'Users',
  'Globe',
  'Shield',
  'Award',
  'Target',
  'Zap',
  'CheckCircle2',
  'BarChart3',
  'Search',
  'CheckCircle',
  'Briefcase',
  'TrendingUp',
  'Star',
  'Heart',
  'Rocket',
  'Lock',
  'Eye',
  'Layers',
  'Network',
  'Cpu',
  'Database',
  'Cloud',
  'Code',
  'Settings',
  'Gauge',
  'Lightbulb',
  'Compass',
  'Map',
  'Navigation',
  'AlertCircle',
  'CheckSquare',
  'Wifi',
  'Radio',
  'Smartphone',
  'Monitor',
  'Headphones',
  'Volume2',
  'Music',
  'Camera',
  'Video',
  'Image',
  'FileText',
  'Download',
  'Upload',
  'Share2',
  'Link',
  'ExternalLink',
  'Copy',
  'Trash2',
  'Edit',
  'Plus',
  'Minus',
  'X',
  'Check',
  'ChevronRight',
  'ChevronDown',
  'Menu',
  'Home',
  'Building2',
  'Factory',
  'Landmark',
  'CreditCard',
  'DollarSign',
  'TrendingDown',
  'PieChart',
  'LineChart',
  'AreaChart',
  'BarChart',
  'Activity',
  'AlertTriangle',
  'Info',
  'HelpCircle',
  'MessageSquare',
  'Mail',
  'Phone',
  'MapPin',
  'Clock',
  'Calendar',
  'Clock3',
  'Watch',
  'Timer',
  'Hourglass',
  'Zap',
  'Battery',
  'Power',
  'Sun',
  'Moon',
  'Cloud',
  'CloudRain',
  'Wind',
  'Droplets',
  'Thermometer',
  'Umbrella',
  'Coffee',
  'Beer',
  'Wine',
  'Utensils',
  'Truck',
  'Car',
  'Plane',
  'Ship',
  'Anchor',
  'Compass',
  'Map',
  'Navigation',
  'Crosshair',
  'Flag',
  'Bookmark',
  'Tag',
  'Tags',
  'Layers',
  'Package',
  'Gift',
  'Inbox',
  'Send',
  'Archive',
  'Trash',
  'AlertCircle',
  'CheckCircle',
  'XCircle',
  'HelpCircle',
  'InfoCircle',
  'Smile',
  'Frown',
  'Meh',
  'Thumbs',
  'Hand',
  'Handshake',
  'Finger',
  'Fist',
  'Wand2',
  'Sparkles',
  'Flame',
  'Wind',
  'Droplet',
  'Leaf',
  'Flower',
  'Feather',
  'Anchor',
  'Anchor2',
  'Anchor3',
];

const columns = [
  { key: 'page',  label: 'Page',  type: 'select',
    options: ['home', 'about', 'social'],
    hint: 'which page this stat appears on' },
  { key: 'value', label: 'Value', type: 'text',   hint: 'e.g. 25+' },
  { key: 'label', label: 'Label', type: 'text',   hint: 'e.g. Years of Experience' },
  { key: 'icon',  label: 'Icon',  type: 'select',   
    options: availableIcons,
    hint: 'Select an icon from the list' },
];

const StatsSection = () => (
  <SheetEditor
    sheetName="Stats"
    title="Statistics"
    description="Numbers shown on the About page and Social Activities page. Each row is one stat card."
    columns={columns}
  />
);

export default StatsSection;
